### ISSUE TITLE
Weather widget - Yahoo data has slow update frequency

### ISSUE THREAD

**Issue by KBJ2007** [tjmarkham/win10widgets#11]
Is the weather widget going to be updated with a more accurate source of data? I've plugged in every zip code in my area and they are all less than accurate, usually 5 degrees and more off with the forecast being even more off.  In contrast, wherever the Dark Sky smartphone app gets its data from might be something to look at as it's very accurate.

Home zip is 95404 BTW.

Definitely appreciate the effort!

**Comment by tjmarkham** [comment]
Thanks for the feedback!

I just looked at the data for 95404, apparently Yahoo hasn't updated it since 11:00 AM PDT. So not really an "accuracy" problem per se, more of a problem with Yahoo's update frequency.

Thanks for the tip about Dark Sky, I just looked at their API (https://developer.forecast.io/). To use their data, the first 1,000 calls are free (those would get used up pretty quickly between all the Win10 Widget users), and then after that it costs money. It's not a lot ($0.0001 per call), but that would quickly add up and I'm not in a financial position right now where I can pay for everyone's weather data.

Unfortunately, I don't know of any other free options for getting weather data that are better than Yahoo. If anyone knows of any please let me know :)

See this thread for more info about switching the Weather widget data source: https://github.com/tjmarkham/win10widgets/issues/6

Update: Looks like Yahoo now has weather data from 12:00 PM PDT for 95404

**Comment by KBJ2007** [comment]
Thanks for checking it out!

**Comment by mindleak** [comment]
I don't know if you'll see this since it's closed, but here's an idea for the more advanced users:

Make a widget using Weather Underground's API: https://www.wunderground.com/weather/api/

Anyone can get a free API key for up to 500 calls per day, which would allow for updating up to like every 3 minutes: https://www.wunderground.com/weather/api/d/pricing.html (I'd program it for like every 5-10 minutes though... but I don't know if each bit of data counts as a call or if just the whole block of data is a call... if it's each bit of data I'm sure like every 30 minutes would still work, I don't know what it'd take though)

So instead of you footing the bill for tons of API calls, have an option in the widget to input the user's own API key before it'll work.
