### ISSUE TITLE
High CPU Usage and Reading

### ISSUE THREAD

**Issue by Octoplayer** [tjmarkham/win10widgets#14]
Hi,
I cannot correlate the CPU stats in WIN10 with the Windows resource Monitor, Win10 says I am averaging say 75-80%, while WRM says it is around 30%, and is the approximately equal across all 4 CPUs.

Also, of that 30%, 20-25% is showing as Rainmaker.exe, i.e Win10 is doing some that chews up far more CPU that the Windows, while WRM is only 5% and doing much the same thing (Monitoring and graphing). Loading and unloading the Widgets, it appears that the "Speakers" widget adds about 15% to the CPU load, and the "Disk Space" widget is about 10%, DateTime is another 5% (as measured on the Win10 CPU widget), 

Could you a) clarify what the CPU meter is displaying, as it not the same as WIndows WMI, b) reduce the CPU being used by some of the widgets?

**Comment by tjmarkham** [comment]
Thanks for the feedback!

The CPU widget retrieves information directly from the Windows Performance Monitor (different than the Resource Monitor and Task Manager) so the problem might be with the Performance Monitor, in which case there's not much I can do about it.

It's hard to tell exactly what percentages you're talking about since you start off by talking about a percentage of a percentage ("of that 30%, 20-25% is showing as Rainmaker.exe"). From then on the percentages you list are ambiguous (e.g. does DateTime take up 5% of the total CPU or 5% of the 20-25% Rainmeter's using?). Can you please clarify the percentages you're seeing? Preferably in terms of total CPU usage instead of as a percentage of a percentage. 

Also, you switch between Windows Resource Monitor measurements ("WRM says it is around 30%") and "Win10" measurements ("as measured on the Win10 CPU widget"). If these two sources are reporting different values on your system ("Win10 says I am averaging say 75-80%, while WRM says it is around 30%") this makes interpreting the data you've provided impossible. Can you please either stick to one measurement tool or provide a full set of data for each? 

Also, your usage of the term "Win10" is very ambiguous. "Win10" refers to the operating system "Windows 10" whereas "Win10 Widgets" refers to this project. When you say "Win10 says I am averaging say 75-80%" it's impossible to know whether you a referring to Windows 10 (the operating system) or Win10 Widgets (this project). In the future, could you please be more clear?

Most people have reported Win10 Widgets to be relatively lightweight (see: https://www.reddit.com/r/Windows10/comments/4so60y/win10_widgets_widgets_that_become_part_of_windows/d5bidjn).  What CPU do you have? Also, what version of Rainmeter are you using?

One other person reported an issue with the CPU usage of the Volume widget, are you using any 3rd party software that might be effecting volume levels? See: https://www.reddit.com/r/Windows10/comments/4so60y/win10_widgets_widgets_that_become_part_of_windows/d5c261l

I've already optimized the widgets as far as CPU usage goes, there's not much more I can do. It might be possible to further optimize the Rainmeter application itself, however I'm not involved in its development so that's out of my domain. The Rainmeter dev team has been working on it for a while though, so I would imagine any optimizations that are possible have already been implemented.

**Comment by Octoplayer** [comment]
Hi,
Thanks – that answers the question about the discrepancy in the CPU stats.
Apologies for any confusion about the CPU usage – the percentages were “raw” and by Win10 CPU widget I meant the the Win10Widget measurements, ie “not % of a %”, so win10Widget was showing 70-75% CPU in use, turning off “Volume” reduced that by 15% to 55-60%. 

Good point about volume controls, I found a DTS Audio control running, but it does not have any graphical overlay as in the Reddit post you referred to. The dark background in the picture marks when I disabled DTS, but as you can see, it did not have any apparent effect.
 
![image](https://cloud.githubusercontent.com/assets/20790453/17340773/8f209540-58e9-11e6-816b-a03be7ae2920.png)

The second screenshot shows the result of re-enabling the Volume control (clock, wifi, disk space and battery all turned off and DTS Audio disabled), the dark background starts at the point I turned on the Volume control. In this case the effect is clear and definite, I was not carrying out any other tasks, so just Windows background activities. 
 
![image](https://cloud.githubusercontent.com/assets/20790453/17340783/9fc981c2-58e9-11e6-84fb-14d319e72356.png)

My processor is AMD A10 PRO7350B R6, 10 Compute cores 4C + 6G  2.10GHz according to the Windows basic info screen.
The Rainmeter version was downloaded a couple of days ago as part of the win10widget package, it reports as V4.4.4 beta July 6 2016. 

Hope that is a bit clearer.

Octo.

**Comment by tjmarkham** [comment]
Thanks for the clarification!

I'm not exactly sure why you're seeing such high CPU usage... it's not like you don't have enough processing power.

We can try increasing the update-interval and see if that helps. You might notice slightly less "smooth" performance depending on how much you increase it.

- Open this file "C:\Users\[Your_User_Name]\Documents\Rainmeter\Skins\Win10 Widgets\Volume\Volume-Medium.ini" 
- Find the line "Update=1" (should be line ~26) 
- Change the value from "1" to "100"
- Save and close the file you just edited.
- Right-click the Volume widget and click "Refresh skin"

Let me know if you see a difference. If you don't, try increasing that update value even more and see if that helps.

**Comment by Octoplayer** [comment]
Hi,
I have tried increasing the Volume interval, there seems to be slight improvement when I changed it to 100 (light to dark background on screenshot), and a more noticeable drop again when I unloaded it (dark to light background). 
![image](https://cloud.githubusercontent.com/assets/20790453/17360713/c7e3660c-5964-11e6-8b30-30e2d14162d4.png)

At 500 any difference is hidden in the noise. The control seems very responsive even at 500, so I will leave it there.
I have just done the same in harddrive-large.ini and Battery-large.ini. As the interval appears to be in ms, I have set that to 10000. DateTime-large.ini to 500.
And the weather does not need updating every millisecond, so I have set that to 10000 in Weather-Extralarge.ini.
CPU is now around 20% on idle, which is a lot more reasonable. Larger intervals would seem to be a sensible default option for many of the controls.

Thanks

**Comment by tjmarkham** [comment]
The "Update" variable doesn't correlate 1:1 to the actual update-rate of each widget. There are multipliers in each section (in Rainmeter this multiplier is referred to as an "UpdateDivider") that change the actual update-rate of specific portions of the code (see: https://docs.rainmeter.net/tips/update-guide/). Most of the UpdateDividers in Win10 Widgets are set to "-1" which means that they will never update except for when they are first loaded and when an "Update" action is triggered.

So, for instance, in the Weather-Extralarge.ini file, the "Update" variable at the top is set to 100, but there is a multiplier that is set to 16425 for the weather-checking portions of the code. 16425 * 100 = 1642500 ms = ~27 minutes, which after taking into account the timing variance Rainmeter introduces, comes out to ~30 minutes. If you change the "Update" variable at the top of the code to 10000, the math would then be 16425 * 10000 = ~2738 minutes = ~46 hours = ~2 days, which doesn't even include the variance Rainmeter introduces. So you've just changed the Weather widget to update about every 2 days.

For the most part, everything is set to "UpdateDivider=-1" in each widget, with the exclusion of what we might call the "driving force" of that widget. So in the Volume widget, the "driving force" would be the [MeasureWin7Audio] section, which interprets volume changes. I would be curious to see what happens when you change "Update" back to "1" for the Volume widget and add "UpdateDivider=500" to the bottom of the [MeasureWin7Audio] section. This would give me a better idea of what's causing the issue.

**Comment by tjmarkham** [comment]
I just did an overhaul of the update-rate system for Win10 Widgets. Even though I wasn't seeing a high CPU load before, I'm seeing an even lower load now... it's usually between 0% and 1% with ten widgets running (and my CPU is worse than yours).

I'm not ready to release an offical update yet, but if you want to check out the updated widgets, you can download the zip here: https://github.com/tjmarkham/win10widgets/archive/master.zip

All you'd have to do is unzip the folder, take the "Win10 Widgets" folder from it, and use it to replace the "Win10 Widgets" folder here: "C:\Users\[Your_User_Name]\Documents\Rainmeter\Skins"

Let me know if you have any questions :)

**Comment by Octoplayer** [comment]
Hi, Thanks for the update, I have also been testing some Update settings, which on my PC seem to work well.

![image](https://cloud.githubusercontent.com/assets/20790453/17584849/b6175936-5fb0-11e6-8516-1303a1df954e.png) 
Changing your new file to 500 for Time update, slight but noticeable reduction in CPU load (where background goes darker).
![image](https://cloud.githubusercontent.com/assets/20790453/17584872/d02b6c04-5fb0-11e6-8237-c532ee75ebeb.png) - Updated Volume - Increases significantly when trying your latest version over my setting file.
I cannot easily compare the files so not quite sure what the differneces are, as it looks like you have saved them with a different CR/LF format, as editing the files now gives this effect:
![image](https://cloud.githubusercontent.com/assets/20790453/17585361/2bc1046e-5fb3-11e6-9c7a-71255454ce00.png)

Instead of original:
![image](https://cloud.githubusercontent.com/assets/20790453/17585512/316d88d2-5fb4-11e6-94a6-6b527fa1b117.png)

Happy to share what I had changed against the original files... attached in zip below.
Regards
[LessCPU.zip](https://github.com/tjmarkham/win10widgets/files/412971/LessCPU.zip)

**Comment by tjmarkham** [comment]
Thanks for the detailed response! Seriously awesome that you're so thorough.

Huh... the End of Line is still "CR/LF" on my local copy. I just downloaded the zip from GitHub and apparently they convert it to just "LF." If you want you can checkout Notepad++ (https://notepad-plus-plus.org/download/); that's what I use to develop these and it handles "CR/LF" and "LF" EOLs equally well. It also has basic syntax highlighting for .ini files which makes them easier to read/edit. In addition, it's very lightweight and has tabs... it's pretty awesome.

It's strange that your system is responding so differently than mine. I have an Intel Core i7-2637M (1.70GHz) which, spec wise, is worse than your CPU (comparison: http://www.cpubenchmark.net/compare.php?cmp%5B%5D=2271&cmp%5B%5D=875). You have more physical cores, higher clock speed... I don't get it. I have 10 widgets open right now and my CPU load is less than 1%.

![rainmeter cpu load](https://cloud.githubusercontent.com/assets/15824310/17595634/c5673f36-5fbb-11e6-8035-8310edc3c906.png)

Question: When you tested the updated .zip, did you swap the entire Win10 Widgets folder? Or did you copy/paste the files you needed into your existing Win10 Widgets folder? I ask because the changes I made were to more than just the specific widget files; there were resource files I changed too which could have an impact on specific widget performance. 

Either way, I think it would be best for you to replace your current Win10 Widgets folder with the one from the zip and then re-edit the the Update variables to your liking (using Notepad++ since GitHub decided to change the EOL characters on us).

Once you do that there are a couple more variables I'd like you to change that I think will improve your CPU load. The skins that use the Windows 10 "accent color" update that variable pretty frequently, I think if we decrease that update rate you'll see lower CPU usage.

**Comment by Octoplayer** [comment]
HI, To answer your question, yes I copied the whole Widgets folder in, having renamed my version first, then refreshed the skins one by one.
I could not find accent color in the .ini files, and will leave them at my version now, as that is doing what I wanted.

Thanks
