### ISSUE TITLE
Error: Spotify Plugin not working

### ISSUE THREAD

**Issue by lmazuel** [tjmarkham/win10widgets#18]
Hi TJ,

Since the update of Spotify this morning, got: Error: Spotify Plugin not working
![image](https://cloud.githubusercontent.com/assets/1050156/17524354/2070ea76-5e13-11e6-91f5-d87957394f74.png)

Needs log or something? Tell me :)

**Comment by lmazuel** [comment]
I tried to re-install the latest one from the website, still the same

**Comment by lmazuel** [comment]
Nevermind, it works :p
Maybe you can just change the message if Spotify is not working? Error is a bit "agressive" :)

**Comment by tjmarkham** [comment]
If something isn't working, isn't that the definition of an "error" ? 

I'm not sure how changing `Error: Spotify plugin not working` to `Spotify plugin not working` would make much of a difference to the user... would you mind elaborating to help me understand?

**Comment by lmazuel** [comment]
For me "Error: Spotify Plugin not working" is more that the plugin itself is broken, I concluded too fast that the cause could have been API change of Spotify.
Actually, I guess you just didn't detect Spotify at the launch of the Widget, so "Spotify not launched" "not found", or something.

But it's a detail and I'm not sure I'm right, keep going your widget it's very great!

**Comment by tjmarkham** [comment]
Thanks!

I understand now, that makes sense... it's funny because your interpretation is exactly what I was going for.

When you see that error message, the widget itself has detected two things:

1. Spotify is open
2. The Spotify plugin isn't getting data

The problem is that the Spotify plugin sometimes just randomly decides to not work. So the error _could_ be signifying that there was an API change, or it could just mean the Spotify plugin is having a bad day. 

I didn't write the code for the plugin, I just made the interface for the widget, so I'm not really in a position to comment on why the plugin sometimes doesn't work. The person that made the Spotify plugin actually just released an update, which I'm going to include in the next release of Win10 Widgets. This is what .raptor (the person who made the plugin) said regarding the update:

> Update!
> Song duration and playing position should now correctly switch from 0:59 to 1:00, instead of 0:60.
> Several other tweaks and fixes.

If you want to install the updated plugin now, you can get it here: https://forum.rainmeter.net/download/file.php?id=12764 

The forum for the Spotify plugin can be found here: https://forum.rainmeter.net/viewtopic.php?f=18&t=17077
