### ISSUE TITLE
Update rate and UpdateDivider improvement

### ISSUE THREAD

**Issue by jsmorley** [tjmarkham/win10widgets#21]
More of a comment than an issue really. I see that you have Update=1 in at least your hard drive skins, and then are driving things with UpdateDivider=-1 on most things and OnChangeAction on a single measure that has UpdateDivider=100.

First off, Rainmeter does not support Update=1. The lowest effective value for Update that will work is 16 milliseconds, and even that is pushing Rainmeter really hard. While I understand the reasoning behind what you are doing, what you are missing is that the one unavoidable thing that Rainmeter will do on each and every Update is to redraw the entire skin. Having Rainmeter tell Windows to redraw the skin window once every 16 milliseconds is just a ton of work I don't think you want to do. While not a huge deal individually, there pretty much has to be some CPU impact if some significant portion of your entire suite is loaded.

My recommendation is to carefully think about what Update really needs to be in any given skin. For instance, checking the hard drive space more than once a second or so is just overkill in my view. I would likely use Update=1000. You can still use the UpdateDivider=-1 on most things and the OnChangeAction on the measures actually reading the disk, as that is a nice touch. Just remove the UpdateDivider=100 from the measures hitting the disk, and let them be driven by Update.

**Comment by tjmarkham** [comment]
Thanks for the feedback!

We must be on the same wavelength... I actually just went through and changed all the UpdateDividers and Update variables a couple days ago and did almost exactly what you're saying :)

Update is now at 100 for everything (except for the Volume widget) with an additional UpdateDivider=10 on most measures to bring them up to one second. The Volume widget has Update=20 since it needs a high-refresh rate to get the bar to move smoothly when dragged. Everything else besides the [MeasureWin7Audio] measure in that widget is at -1 and changes with OnChangeActions, so it seems to be doing okay.

I also added "DefaultUpdateDivider=-1" to everything and removed all the individual "UpdateDividers=-1" lines. I don't know how I missed that originally, it's much simpler now.

I've definitely seen an improvement... the CPU load I'm seeing now is usually between 0% and 1% with 10 skins running, and my laptop isn't crazy fast (it's from ~2012). I'm waiting to change a couple more things before I put out the new release, but the changes are up on GitHub.

Commit: https://github.com/tjmarkham/win10widgets/commit/3505a4e0abb508a4e92506d38fc53a6ab664961e

Comment in other thread: https://github.com/tjmarkham/win10widgets/issues/14#issuecomment-238384903

The reason I originally had "Update=1" was just to keep the math simple since I was using UpdateDividers on literally everything. I made the (incorrect) assumption that the lower bound of 16 was setup so that if the overall update rate of a measure was greater than 16, the Update variable could have a lower number than 16. So when I had UpdateDivder=100, I thought that the update rate of the measure would be 100 (Update=1 * UpdateDivder=100 = 100). Turns out the lower bound of 16 is a hard limit, and the update rate was actually 1600 (Update=16 * UpdateDivder=100 = 1600) even when Update was set to 1.

**Comment by tjmarkham** [comment]
Oh, and the reason I'm using Update=100 and UpdateDivider=10 (instead of just setting Update=1000) is that for each widget with a background, I have a measure in place (imported from "#@#background.ini") that changes the widget's background border depending on whether or not the widget is at an edge of the screen (I call this "auto-border").

The "auto-border" measure needs to have an update rate at ~100 to keep the auto-border action smooth. Since the measure is all IfConditions (with DynamicVariables=1 and IfConditionMode=0), it's not resource intensive because it doesn't check the conditions on every update cycle, it just checks the conditions when the CURRENTCONFIG variables change.

So, for example, if you have the DateTime widget in the middle of your screen, the widget background will have a 1px semi-transparent white border on all its edges. If you move the widget to the right side of your screen, the right border will disappear; if you move it to the left side of your screen, the left border will disappear; etc.

That way, the black background of the widget can "touch" the edge of the screen and still leave the rest of the semi-transparent white border intact.
