### ISSUE TITLE
Widget request - Battery saver indicator/toggle

### ISSUE THREAD

**Issue by guyyst** [tjmarkham/win10widgets#22]
Currently the battery widget doesn't indicate weather or not the battery saver option is enabled (Charging however has an indicator).

Alongside that feature, could we get the option to toggle battery saver mode by interacting with the battery widget in a certain way? I don't know if rainmeter allows for easily accessible toggles like that.

**Comment by tjmarkham** [comment]
Thanks for the feedback!

I wanted to implement this feature, but couldn't find a way to do it. If you open the Battery-Large.ini file (`C:\Users\[Your_User_Name]\Documents\Rainmeter\Skins\Win10 Widgets\Battery\Battery-Large.ini`) you'll see a note about it at the top.

The power plugin (documentation here: https://docs.rainmeter.net/manual/plugins/power/) doesn't offer any way to see when battery-saver mode is active. I looked at both "PowerState=Status" and "PowerState=Status2" from the power plugin, but neither provided any information about battery-saver mode.

Some might suggest that I hard-code the widget to show the battery-saver icon at 20%, but the battery-saver level isn't a a hard-coded value in Windows 10 and can be adjusted by the user.  If the value was hard-coded in the Battery widget and a user adjusted their battery-saver level in Windows 10, the widget would no longer accurately indicate when battery-saver was active.

Since the Battery widget has no way of indicating when battery-saver is active, I'm going to hold off on trying to implement a battery-saver toggle. It would be kind of strange to have a toggle that didn't provide any feedback within the widget.
