### ISSUE TITLE
How do you turn off seconds in the Date/Time Widget?

### ISSUE THREAD

**Issue by kendoori** [tjmarkham/win10widgets#59]
the ticking seconds is very distracting. Tried modifying the .ini file but ended up mucking up the layout.

**Comment by don199** [comment]
I had the same issue and here's what I did.  You have to comment out (by using a semicolon at the beginning of the line) the parts of datetime-Large.ini that deal with seconds and you also have to adjust some spacing so that the date doesn't run into the area where the seconds were being displayed. I couldn't figure out exactly what I changed since the original as far as spacing, but here's a pastebin of my DateTime-Large.ini that should work (make a backup of yours first) http://pastebin.com/raw/Kjq6ExHX

**Comment by kendoori** [comment]
Thank you so much for this. It worked!
