### ISSUE TITLE
Weather widget - Switch to weather.com feed

### ISSUE THREAD

**Issue by darcilicious** [tjmarkham/win10widgets#6]
It seems like the weather.com feed is a bit more stable than the Yahoo! one...

**Comment by tjmarkham** [comment]
Have you had particular issues with the Weather widget? The Yahoo service I'm using is based on YQL and has seemed very stable; it's not the same Yahoo feed that almost all other Rainmeter skins used to use.

**Comment by darcilicious** [comment]
From the Weather-ExtraLarge.in file:

; - Sometimes the weather data feed goes down. Nothing I can do about 
;	that. If you know of a better source for weather data please let me 
;	know :)

And yes, at one point, the temperature was not updating this afternoon  (for about 30 minutes) compared to both the weather.yahoo.com website and the Yahoo! app on my iPhone.

If you're comfortable with continuing with yahoo's feed, I'm fine with it too :) But you did ask ;)

**Comment by tjmarkham** [comment]
I put that note in there when I first started developing the Weather widget a few months ago when I noticed an outage or two, but since then I haven't seen any issues.

The Weather widget updates about every half hour so it's not constantly using network resources. Is that what you were seeing? Or did the widget say something like "Connection error"?

I definitely appreciate the feedback. I'll probably switch to the weather.com feed eventually since Yahoo's fate is somewhat uncertain after being bought by Verizon.

Do you have a URL for the Weather.com feed API by any chance? I just tried to find it on Google and didn't have much luck.

I did find this post (https://forum.rainmeter.net/viewtopic.php?f=13&t=23289) which is pretty useful, but what I really need is a list of what the condition codes represent so I can match icons to them.

**Comment by darcilicious** [comment]
Ah I see. 

No, no connection errors so overall it seems to be good enough :)

I haven't poked around the updated APIs in a while but I bet someone over at the Rainmeter forums knows something :) 

At any rate, good work on this suite, it's really nice!

**Comment by tjmarkham** [comment]
Thanks! Glad you like it :)

And thanks for the tip about the weather.com feed. When I first looked at different weather feeds a few months ago I didn't think the weather.com one had as much data as the Yahoo feed, but giving it another look it seems to have the exact same data which is awesome. 

Just need to find a list of what the condition codes represent... If anyone sees this and has any leads please let me know :)

**Comment by tjmarkham** [comment]
Did a little more digging, and I don't think weather.com is going to work. Reason being... they use different codes for their locations, and I can't seem to find an API that will let me lookup those codes like I can with Yahoo.

Yahoo lets me query location codes based on a ton of factors (zip code, city, etc.) whereas I can't find _any_ system to query for the codes weather.com uses.

The best I could find was this: https://weather.codes/ but the search function is abysmal.
