### ISSUE TITLE
Weather widget - Auto-location doesn't work for all locations

### ISSUE THREAD

**Issue by Wanny** [tjmarkham/win10widgets#7]
With Auto-Location the widgets displays the following message:

Connection Error
Try again in a few seconds

And no matter how many times I press the Refresh button, it doesn't work. However, setting the location manually doesn't produce any error messages.

Just for reference, I'm using Rainmeter 4.0.0 beta

**Comment by Wanny** [comment]
I just checked the log and I see this each time I press the Refresh button:

![image](https://cloud.githubusercontent.com/assets/569307/17267842/0ee33ae6-55eb-11e6-8216-cb86b3e5efe4.png)

**Comment by Wanny** [comment]
OK, found the error. In Weather-ExtraLarge.ini there's this line in the [MeasureZipCode] section:

<pre>URL=http://ipinfo.io/postal</pre>

Trying that URL in a browser just returns the "undefined" text.

If I change the URL to just **http://ipinfo.io** it works fine.

**Comment by tjmarkham** [comment]
Hi, thanks for the feedback!

The Weather widget uses http://ipinfo.io/postal for the auto-location feature since it was the best free location provider I could find. It checks your IP address against a database to determine your geolocation, and sometimes it either doesn't work or provides inaccurate results since it's not GPS-based. That's one of the reasons why I added the ability to set the weather location manually.

If anyone knows of a better free location provider, please let me know and I'll look into integrating it :)

**Comment by Wanny** [comment]
Appearently the guys at ipinfo.io disabled the "postal" field if an IP address isn't manually entered in the URL

**Comment by tjmarkham** [comment]
That's not the case for me and most other users. I think it must have to do with your specific IP.

**Comment by Wanny** [comment]
Seems that it's my location. Makes sense, I don't live in the US so that's why it doesn't return a postal code.

**Comment by tjmarkham** [comment]
Ah, I didn't realize other countries wouldn't have postal codes. Can you do me a favor? Go to this URL: http://ipinfo.io/geo and copy/paste what you see. 

You can leave out anything you don't feel like sharing (IP, lat/long, etc.), I'm just curious to see which fields work for you and which don't.

**Comment by Wanny** [comment]
{
  "ip": "190.xx.xx.xx",
  "city": "Santiago",
  "region": "Santiago Metropolitan",
  "country": "CL",
  "loc": "-33.4500,-70.6667"
}

**Comment by tjmarkham** [comment]
Awesome, thanks. I'll look into using the city/region/country combo instead of the postal code.

**Comment by tjmarkham** [comment]
I just updated the **Weather-ExtraLarge.ini** file to use the city/region/country instead of the postal code. Would you mind trying it out and letting me know how it works? To try it out:

- Go to the file on GitHub here: https://github.com/tjmarkham/win10widgets/blob/master/Win10%20Widgets/Weather/Weather-ExtraLarge.ini
- Find the "Raw" button. It's in the header of the "code" area to the right.
- Right-click the "Raw" button and click "Save link as..."
- In the save dialog, navigate to:

`C:\Users\[Your_User_Name]\Documents\Rainmeter\Skins\Win10 Widgets\Weather`
- Save the file. When Windows asks if you want to replace the current file, click "Yes."
- Right-click the "Weather" widget and click "Refresh skin."

I think that should work, I tested the URL endpoints with the location data you gave me and it seemed to work, but I want to make 100% sure it works in the real world before I put this in the next update. Set the Weather widget to "Auto-location" and let me know if it works.

Thanks!

**Comment by Wanny** [comment]
It works perfectly now. Thank you for your quick answers!

It'd be nice if other people tested it too.

**Comment by tjmarkham** [comment]
You're welcome! And thanks for your help!

I'll do my best to get it in the hands of other international users before it goes live. I've had a few other people tell me auto-location didn't work for them.

**Comment by ridanlukita** [comment]
How can i set the widget to show data from my geo-location and how to Set the Weather widget to "Auto-location"?
*right now i only get location based on my IP address (which about 150km away from geo-location)

**Comment by AlbertoManni** [comment]
Hello TJ, I am in Sheffield, UK, and don't know hot to set my weather location... it shows as Singapore, a bit off to the east... can you help?
